---

- name: Install
  include: install.yml
  tags:
    - install

- name: Configure
  include: configure.yml
  tags:
    - configure

- name: Configure S3 Sync
  include: s3-sync.yml
  tags:
    - configure

- supervisorctl:
    name: hivemq
    state: started

- name: Ensure for HiveMQ is started
  wait_for:
    port: "{{ hivemq_port }}"
